### ISSUE TITLE
temp files not moving

### ISSUE THREAD

**Issue by datawhores** [datawhores/ofscraper#5] opened 2023-04-06 14:39 UTC
@outsdr01
https://github.com/excludedBittern8/ofscraper/issues/3

Opening a seperate issue for this

**Comment by excludedBittern8** [comment] 2023-04-06 14:49
Can you download the latest version, and see if the issue is fixed?
version 1.60+

**Comment by outsdr01** [comment] 2023-04-07 13:38
Thanks you ! I am receiving the following errors:

Progress: (0 photos, 0 videos, 196 skipped || 196/197||0.0 MB): : 195it [00:32,  8.04it/s]Traceback (most recent call last):
  File "M:\!!Python\lib\site-packages\src\utils\download.py", line 138, in download
    path_to_file = trunicate(pathlib.Path(path,f"{filename}"))
  File "M:\!!Python\lib\site-packages\src\utils\download.py", line 346, in trunicate
    if platform.system() == 'Windows' and len(path)>256:
TypeError: object of type 'WindowsPath' has no len()

**Comment by excludedBittern8** [comment] 2023-04-07 13:50
You need to update to the latest version

**Comment by outsdr01** [comment] 2023-04-07 15:55
PS M:\ofscraper-main> ofscraper -v
ofscraper 1.65

? Which area(s) would you like to scrape? (Press ENTER to continue) ['Timeline', 'Archived', 'Highlights', 'Stories', '
Messages']
Name: XXXXXX | Username: XXXXXX | ID: XXXXXX | Joined: 2020-02-27T00:00:00+00:00
- 37 posts
 -- 70 photos
 -- 19 videos
 -- 0 audios
- 8 archived posts
Pages Progress: 2: : 2it [00:07,  3.55s/it]         g timeline media...
 + Getting timeline media...
 + Getting pinned media...
 + Getting archived media...
Pages Progress: 3: : 3it [00:05,  1.77s/it]   Getting messages...
 + Getting messages...
 + Getting highlights and stories...
Skipping previously downloaded
Media left for download 154

Downloading to C:\Users\Outsdr\Data\ofscraper/{model_username}/{responsetype}/{mediatype}/


Progress: (0 photos, 0 videos, 0 skipped || 0/154||0): 0it [00:00, ?it/s]Traceback (most recent call last):
  File "M:\!!Python\lib\site-packages\src\utils\download.py", line 138, in download
    path_to_file = trunicate(pathlib.Path(path,f"{filename}"))
  File "M:\!!Python\lib\site-packages\src\utils\download.py", line 346, in trunicate
    if platform.system() == 'Windows' and len(path)>256:
TypeError: object of type 'WindowsPath' has no len()

Is it because I am not using a default installation path for Python?

**Comment by excludedBittern8** [comment] 2023-04-07 19:13
No I'm going to push a fix in like 10 minutes

**Comment by excludedBittern8** [comment] 2023-04-07 22:30
Sorry for the delay the new push should work 
Make sur you have win32_setctime installed as well

**Comment by excludedBittern8** [comment] 2023-04-08 02:19
Version 1.72 should fix the error

**Comment by outsdr01** [comment] 2023-04-09 15:48
Good news is, it's downloading again. 

Bad news, it's still not relocating the downloaded files. I've got a workaround in place that I can use though, so it's not a priority to get this fixed, for me at least. 

How can I support you?

**Comment by datawhores** [comment] 2023-04-09 18:36
There are lots of ways to support. I added some support links to the repo, but getting feedback on bugs is also very helpful.

I plan on removing the temp files. They aren't really necessary unless your using the --dupe arg

**Comment by datawhores** [comment] 2023-04-10 06:18
Also if you run into the file is being used by another process error. Knowing which process is blocking would be helpful.

**Comment by outsdr01** [comment] 2023-04-11 19:06
I have been getting a some of those, but it's hard to track down what's blocking because there's no time stamp. Plus, powershell doesn't record an error in the event log. 

The only thing I even found around the same time was a Security warning:

Log Name:      System
Source:        Microsoft-Windows-DistributedCOM
Date:          4/11/2023 9:40:06 AM
Event ID:      10016
Task Category: None
Level:         Warning
Keywords:      Classic
User:          MINION\Outsdr
Computer:      Minion
Description:
The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{8BC3F05E-D86B-11D0-A075-00C04FB68820}
 and APPID 
{8BC3F05E-D86B-11D0-A075-00C04FB68820}
 to the user MINION\Outsdr SID (S-1-5-21-4204490277-530115684-707425520-1001) from address LocalHost (Using LRPC) running in the application container Unavailable SID (S-1-15-2-2034283098-2252572593-1072577386-2659511007-3245387615-27016815-3920691934). This security permission can be modified using the Component Services administrative tool.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-DistributedCOM" Guid="{1B562E86-B7AA-4131-BADC-B6F3A001407E}" EventSourceName="DCOM" />
    <EventID Qualifiers="0">10016</EventID>
    <Version>0</Version>
    <Level>3</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8080000000000000</Keywords>
    <TimeCreated SystemTime="2023-04-11T15:40:06.6657156Z" />
    <EventRecordID>20243979</EventRecordID>
    <Correlation ActivityID="{4628a79b-88a2-4c23-be52-2abbf176d69a}" />
    <Execution ProcessID="1200" ThreadID="18520" />
    <Channel>System</Channel>
    <Computer>Minion</Computer>
    <Security UserID="S-1-5-21-4204490277-530115684-707425520-1001" />
  </System>
  <EventData>
    <Data Name="param1">application-specific</Data>
    <Data Name="param2">Local</Data>
    <Data Name="param3">Activation</Data>
    <Data Name="param4">{8BC3F05E-D86B-11D0-A075-00C04FB68820}</Data>
    <Data Name="param5">{8BC3F05E-D86B-11D0-A075-00C04FB68820}</Data>
    <Data Name="param6">MINION</Data>
    <Data Name="param7">Outsdr</Data>
    <Data Name="param8">S-1-5-21-4204490277-530115684-707425520-1001</Data>
    <Data Name="param9">LocalHost (Using LRPC)</Data>
    <Data Name="param10">Unavailable</Data>
    <Data Name="param11">S-1-15-2-2034283098-2252572593-1072577386-2659511007-3245387615-27016815-3920691934</Data>
  </EventData>
</Event>

**Comment by datawhores** [comment] 2023-04-20 13:26
This may be caused by dupe media

Can you test the new test branch latest commit

**Comment by outsdr01** [comment] 2023-04-21 11:55
I downloaded the files, but I'm not sure how to get them to install. pip install ofscraper (after uninstalling) just re-installs v 1.75.

**Comment by datawhores** [comment] 2023-04-21 22:09
I think you would have to activate the virtualenv

Then do poetry install or update

**Comment by outsdr01** [comment] 2023-04-22 16:38
PS M:\ofscraper-test> pip uninstall ofscraper
WARNING: Skipping ofscraper as it is not installed.
PS M:\ofscraper-test> poetry install
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: ofscraper (1.80)
PS M:\ofscraper-test> ofscraper -v
ofscraper : The term 'ofscraper' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ofscraper -v
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ofscraper:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS M:\ofscraper-test> poetry update
Updating dependencies
Resolving dependencies... (1.2s)

No dependencies to install or update
PS M:\ofscraper-test> ofscraper -v
ofscraper : The term 'ofscraper' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ofscraper -v
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ofscraper:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS M:\ofscraper-test>

**Comment by datawhores** [comment] 2023-04-22 19:37
Poetry is suppose to auto detect virtuaenv

https://virtualenv.pypa.io/en/latest/installation.html

When I install it this way the binary ends up with the venv folder.

Also I'm planning on releasing this version soon to pip. I just have a little bit more testing to do

**Comment by outsdr01** [comment] 2023-04-22 19:50
![pipx](https://user-images.githubusercontent.com/84547341/233803557-91a8c14c-f798-4911-a7cb-c4ae51bfe4b2.PNG)

PS M:\ofscraper-test> poetry install
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: ofscraper (1.80)
PS M:\ofscraper-test> poetry update
Updating dependencies
Resolving dependencies... (3.4s)

No dependencies to install or update
PS M:\ofscraper-test> ofscraper
ofscraper : The term 'ofscraper' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ofscraper
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ofscraper:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS M:\ofscraper-test>

I'm going to try installing the main ofscraper using poetry, and then updating.

**Comment by outsdr01** [comment] 2023-04-22 19:51
Did not work. 

PS M:\ofscraper-main> poetry install
Creating virtualenv ofscraper-E9NmgSJU-py3.10 in C:\Users\Outsdr\AppData\Local\pypoetry\Cache\virtualenvs
Installing dependencies from lock file

Package operations: 40 installs, 1 update, 0 removals

  • Installing idna (3.4)
  • Installing sniffio (1.3.0)
  • Installing anyio (3.6.2)
  • Installing certifi (2022.12.7)
  • Installing colorama (0.4.6)
  • Installing h11 (0.14.0)
  • Installing hpack (4.0.0)
  • Installing hyperframe (6.0.1)
  • Installing mdurl (0.1.2)
  • Installing six (1.16.0)
  • Installing soupsieve (2.4)
  • Installing wcwidth (0.2.6)
  • Installing beautifulsoup4 (4.12.0): Pending...
  • Installing charset-normalizer (3.1.0): Installing...
  • Installing beautifulsoup4 (4.12.0)
  • Installing charset-normalizer (3.1.0)
  • Installing h2 (4.1.0)
  • Installing httpcore (0.16.3)
  • Installing log-symbols (0.0.14)
  • Installing lz4 (4.3.2)
  • Installing markdown-it-py (2.2.0)
  • Installing pfzy (0.3.4)
  • Installing prompt-toolkit (3.0.38)
  • Installing pycryptodomex (3.17)
  • Installing pygments (2.14.0)
  • Installing python-dateutil (2.8.2)
  • Installing rfc3986 (1.5.0)
  • Installing spinners (0.0.24)
  • Installing termcolor (2.2.0)
  • Installing urllib3 (1.26.15)
  • Installing arrow (1.2.3): Installing...
  • Installing browser-cookie3 (0.17.1)
  • Installing arrow (1.2.3)
  • Installing browser-cookie3 (0.17.1)
  • Installing bs4 (0.0.1)
  • Installing halo (0.0.31)
  • Installing httpx (0.23.3)
  • Installing inquirerpy (0.3.4)
  • Installing requests (2.28.2)
  • Installing rich (13.3.2)
  • Installing schedule (1.1.0)
  • Updating setuptools (67.6.1 -> 67.6.0)
  • Installing tenacity (8.2.2)
  • Installing tqdm (4.65.0)
  • Installing win32-setctime (1.1.0)

Installing the current project: ofscraper (1.75)
PS M:\ofscraper-main>

PS M:\ofscraper-test> poetry update
Updating dependencies
Resolving dependencies... (1.2s)

No dependencies to install or update
PS M:\ofscraper-test> poetry install
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: ofscraper (1.80)
PS M:\ofscraper-test> ofscraper -v
ofscraper : The term 'ofscraper' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ofscraper -v
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ofscraper:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS M:\ofscraper-test>

**Comment by outsdr01** [comment] 2023-04-22 19:55
Should OFScraper be in PATH? 

![image](https://user-images.githubusercontent.com/84547341/233803935-a78d7f9b-a8cf-43d2-b97d-6b52707f0ebc.png)

**Comment by datawhores** [comment] 2023-04-23 08:07
It would probably help you should join the discord. Because their are users who used windows as there daily operating system.

I know a few have gotten this to work

**Comment by outsdr01** [comment] 2023-04-26 11:53
I have version 1.80 installed now, and everything is working, except that all files are still being left in the %user%\Data\ofscraper folder.

**Comment by datawhores** [comment] 2023-04-26 12:32
I think that is the default

What does your config file look like?

**Comment by outsdr01** [comment] 2023-04-28 11:56
Indeed, my config file needed re-set. Everything works perfectly now. Thank you!

**Closed** 2023-04-28 12:01 UTC
